version: "3.9"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_volume:/var/lib/postgresql/data
volumes:
  database_volume:
