default: &default
  adapter: postgresql
  host: database
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: trz_development

test:
  <<: *default
  database: trz_test

production:
  <<: *default
  database: trz
